services: 
  postgres: 
    image: postgres:latest
    hostname: pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: Paintings_Web_App
    ports:
      - "5432:5432"

  app:
      build: 
        context: .
        dockerfile: Dockerfile
      hostname: paint
      environment:
        IN_CONTAINER: true
      ports:
        - "8080:8080"
      depends_on:
        - postgres

